export const locationOptions = [
  { value: "remote", label: "Remote" },
  { value: "jakarta", label: "Jakarta" },
  { value: "surabaya", label: "Surabaya" },
  { value: "bandung", label: "Bandung" },
  { value: "medan", label: "Medan" },
  { value: "semarang", label: "Semarang" },
  { value: "makassar", label: "Makassar" },
  { value: "palembang", label: "Palembang" },
  { value: "tangerang", label: "Tangerang" },
  { value: "depok", label: "Depok" },
  { value: "bekasi", label: "Bekasi" },
  { value: "batam", label: "Batam" },
  { value: "bogor", label: "Bogor" },
  { value: "yogyakarta", label: "Yogyakarta" },
  { value: "malang", label: "Malang" },
  { value: "denpasar", label: "Denpasar" },
  { value: "pekanbaru", label: "Pekanbaru" },
  { value: "bandar lampung", label: "Bandar Lampung" },
  { value: "padang", label: "Padang" },
  { value: "samarinda", label: "Samarinda" },
  { value: "balikpapan", label: "Balikpapan" },
  { value: "tasikmalaya", label: "Tasikmalaya" },
  { value: "pontianak", label: "Pontianak" },
  { value: "banjarmasin", label: "Banjarmasin" },
  { value: "cimahi", label: "Cimahi" },
  { value: "manado", label: "Manado" },
  { value: "jambi", label: "Jambi" },
  { value: "surakarta", label: "Surakarta (Solo)" },
  { value: "mataram", label: "Mataram" },
  { value: "ambon", label: "Ambon" },
  { value: "kupang", label: "Kupang" },
  { value: "palu", label: "Palu" },
  { value: "jayapura", label: "Jayapura" },
  { value: "banda aceh", label: "Banda Aceh" },
  { value: "pekalongan", label: "Pekalongan" },
  { value: "cirebon", label: "Cirebon" },
  { value: "kediri", label: "Kediri" },
  { value: "binjai", label: "Binjai" },
  { value: "tegal", label: "Tegal" },
  { value: "kendari", label: "Kendari" },
  { value: "bengkulu", label: "Bengkulu" },
  { value: "ternate", label: "Ternate" },
  { value: "serang", label: "Serang" },
  { value: "magelang", label: "Magelang" },
  { value: "sukabumi", label: "Sukabumi" },
  { value: "cilegon", label: "Cilegon" },
  { value: "gorontalo", label: "Gorontalo" },
  { value: "probolinggo", label: "Probolinggo" },
  { value: "madiun", label: "Madiun" },
  { value: "tarakan", label: "Tarakan" },
  { value: "pangkal pinang", label: "Pangkal Pinang" },
  { value: "cianjur", label: "Cianjur" },
  { value: "karawang", label: "Karawang" },
  { value: "bitung", label: "Bitung" },
  { value: "lhokseumawe", label: "Lhokseumawe" },
  { value: "tanjung pinang", label: "Tanjung Pinang" },
  { value: "pasuruan", label: "Pasuruan" },
  { value: "dumai", label: "Dumai" },
  { value: "tanjung balai", label: "Tanjung Balai" },
  { value: "bontang", label: "Bontang" },
  { value: "palangkaraya", label: "Palangkaraya" },
  { value: "lubuklinggau", label: "Lubuklinggau" },
  { value: "blitar", label: "Blitar" },
  { value: "banjarbaru", label: "Banjarbaru" },
  { value: "purwokerto", label: "Purwokerto" },
  { value: "pematangsiantar", label: "Pematangsiantar" },
  { value: "tebing tinggi", label: "Tebing Tinggi" },
  { value: "sibolga", label: "Sibolga" },
  { value: "prabumulih", label: "Prabumulih" },
  { value: "mojokerto", label: "Mojokerto" },
  { value: "padang sidempuan", label: "Padang Sidempuan" },
  { value: "bukittinggi", label: "Bukittinggi" },
  { value: "payakumbuh", label: "Payakumbuh" },
  { value: "salatiga", label: "Salatiga" },
  { value: "parepare", label: "Parepare" },
  { value: "langsa", label: "Langsa" },
  { value: "sorong", label: "Sorong" },
  { value: "metro", label: "Metro" },
  { value: "batu", label: "Batu" },
  { value: "baubau", label: "Baubau" },
  { value: "sungai penuh", label: "Sungai Penuh" },
  { value: "solok", label: "Solok" },
  { value: "padang panjang", label: "Padang Panjang" },
  { value: "sawah lunto", label: "Sawah Lunto" },
  { value: "pariaman", label: "Pariaman" },
  { value: "sabang", label: "Sabang" },
  { value: "tomohon", label: "Tomohon" },
  { value: "subulussalam", label: "Subulussalam" },
  { value: "kotamobagu", label: "Kotamobagu" },
  { value: "tual", label: "Tual" },
  { value: "tidore", label: "Tidore" },
  { value: "singkawang", label: "Singkawang" },
  { value: "mamuju", label: "Mamuju" },
  { value: "sofifi", label: "Sofifi" },
  { value: "sungai raya", label: "Sungai Raya" },
  { value: "jember", label: "Jember" },
  { value: "purwakarta", label: "Purwakarta" },
  { value: "garut", label: "Garut" },
  { value: "kudus", label: "Kudus" },
];
